// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi3dziqqe1HaFynyi6ZZ_xLnMmCZ8P6As',
    appId: '1:959508689617:web:92f62beb51288f681c8bf0',
    messagingSenderId: '959508689617',
    projectId: 'driver-app-f8c2c',
    authDomain: 'driver-app-f8c2c.firebaseapp.com',
    storageBucket: 'driver-app-f8c2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiATdNhedr9tQEmkkeE2XQxbdKf5AMkE',
    appId: '1:959508689617:android:bd2a747f26d4160d1c8bf0',
    messagingSenderId: '959508689617',
    projectId: 'driver-app-f8c2c',
    storageBucket: 'driver-app-f8c2c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi3dziqqe1HaFynyi6ZZ_xLnMmCZ8P6As',
    appId: '1:959508689617:web:af84923ca2ae72331c8bf0',
    messagingSenderId: '959508689617',
    projectId: 'driver-app-f8c2c',
    authDomain: 'driver-app-f8c2c.firebaseapp.com',
    storageBucket: 'driver-app-f8c2c.firebasestorage.app',
  );
}
